### ISSUE TITLE
Query about sourcing pictures (no Issue)

### ISSUE THREAD

**Issue by SafwanKhan112358** [gheorghedarle/Xamarin-Formula1#1]
Hi there, Great Application! It looks super sleek and easy-to-use. 

I was wondering how you sourced pictures of the F1 drivers? I saw you mentioned something about Formula 1 Images API . I did a quick google search but didn't find anything

Thanks, Safwan

**Comment by gheorghedarle** [comment]
Hello @SafwanKhan112358, Formula 1 Images API is built by me, it is a simple API built in nodejs just to serve images for the application. You can find the source of the API here https://github.com/gheorghedarle/Xamarin-Formula1/tree/main/Formula1-Images-API. To run the app just double-click on **npm-install.bat** and then **npm-start.bat** or just **npm install** then **npm start** in a terminal.

**Comment by SafwanKhan112358** [comment]
Right;

correct me if wrong, but I think npm is for like node js right?

How would I install this through python? It's through the pip command, but
would the exact installation procedure/commands be?

thanks, Safwan
ᐧ

**Comment by gheorghedarle** [comment]
I am not sure if you can install the node.js and npm using python. You can follow the instructions from here: https://nodejs.org/en/download/package-manager/ or https://docs.npmjs.com/downloading-and-installing-node-js-and-npm
