### ISSUE TITLE
Build errors, failed llinking files Severity	Code	formula1:style/Theme.AppCompat.Light.NoActionBar not found.	

### ISSUE THREAD

**Issue by papyr** [gheorghedarle/Xamarin-Formula1#5]
Hello this is a great sample, but I am facing some build errors.

I see this is core 2.1, will this work with .Net core 8 LTS, which seems to be much faster and the nugets are updated. Also how can we calendar updates in app, reminders to watch the F1

![image](https://github.com/gheorghedarle/Xamarin-Formula1/assets/12733414/2585f271-f578-47dc-a409-2228ffd3a7c8)

**Comment by gheorghedarle** [comment]
Hello @papyr the app is using .net standard 2.1, do you want to update to .net MAUI?

**Comment by papyr** [comment]
yes please to MAUI
